name: Cache Dependencies

on:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-24a374a   
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-24a374a      

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
